/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/eva.glb 
Author: katiekangaroo (https://sketchfab.com/katiekangaroo)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/eva-d434dfc3cb9244fbba83407ccabdd523
Title: Eva
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eva.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.743, 2.136, -0.239]} rotation={[0.058, 0.025, 0.009]}>
        <mesh geometry={nodes.body__0.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.body__0_1.geometry} material={materials['Scene_-_Root']} />
      </group>
      <mesh geometry={nodes.head_screen___0.geometry} material={materials['Scene_-_Root']} position={[0.566, 1.65, -0.324]} rotation={[0.231, 0.174, -0.153]} />
      <mesh geometry={nodes.eyes__0.geometry} material={materials['Scene_-_Root']} position={[0.63, 2.47, 0.742]} rotation={[0.114, -0.198, -0.316]} />
      <mesh geometry={nodes.head_white___0.geometry} material={materials['Scene_-_Root']} position={[0.581, 1.69, -0.292]} rotation={[0.243, 0.147, -0.155]} />
      <mesh geometry={nodes.arm__0.geometry} material={materials['Scene_-_Root']} position={[-0.316, 1.092, -0.285]} rotation={[0.104, 0.083, -0.316]} />
    </group>
  )
}

useGLTF.preload('/eva.glb')
